repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: docs/.*|tests/data_context/fixtures/bad_yml/great_expectations\.yml
      - id: end-of-file-fixer
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls
      - id: trailing-whitespace
        exclude: docs/.*
      - id: requirements-txt-fixer
        exclude: docs/.*
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        exclude: docs/.*
