name: stalebot

on:
 issues:
   types: [reopened]
 schedule:
   - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: actions/stale@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?\n\nThis issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-pr-message: 'Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?\n\nThis issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        days-before-stale: 120
        days-before-close: 7
        stale-issue-label: stale
        stale-pr-label: stale
        exempt-issue-label: stalebot-exempt
        exempt-pr-labels: stalebot-exempt
        operations-per-run: 30
        main: 'lib/main.js'
        debug-only: false
